name: toml-test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: replace group_id value with org_id
        shell: pwsh
        run: |
          # Org ID
          $org_id = "5678"
          # File path
          $tomlFile = "Cargo.toml"

          # Read file content
          $content = Get-Content $tomlFile

          # Replace the specific key-value pair
          $content = $content -replace '^(group_id\s*=\s*)".*"', '${1}${org_id}'

          # Write the updated content back to the file
          Set-Content -Path $tomlFile -Value $content

          cat ${{GITHUB.WORKSPACE}}/Cargo.toml

